import { AppProvider } from '@/context/appContext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
type Props ={
  children:React.ReactNode;
  parallel:React.ReactNode
}

export default function RootLayout(props:Props) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
        {props.children}
        {props.parallel}
        </AppProvider>
        </body>
    </html>
  )
}
